// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package database

import (
	"time"

	"github.com/google/uuid"
)

type Book struct {
	ID          uuid.UUID
	Title       string
	Author      string
	Description string
	Pages       int32
	CreatedAt   time.Time
	UpdatedAt   time.Time
	UserID      uuid.UUID
}

type User struct {
	ID        uuid.UUID
	Username  string
	Email     string
	CreatedAt time.Time
	UpdatedAt time.Time
	ApiKey    string
}
