### Check server health
GET http://localhost:3000

### Check v1 route health
GET http://localhost:3000/v1

### Error route
GET http://localhost:3000/v1/error

### Get user by api key
GET http://localhost:3000/v1/users
Content-Type: application/json
Authorization: ApiKey da645d25d2a4baa2e92d3a82b337ad89e4da0e758bf83edb311710eea680a2ea

### Creat new user
POST http://localhost:3000/v1/users

{
    "username": "Buipe Albany",
    "email": "albany@nexus.com"
}

### Creat new book
POST http://localhost:3000/v1/books
Content-Type: application/json
Authorization: ApiKey da645d25d2a4baa2e92d3a82b337ad89e4da0e758bf83edb311710eea680a2ea

{
    "title": "The 48 Laws of Power",
    "author": "Robert Greene",
    "description": "Excellent book on power dynamics"
}

### Get all books
GET http://localhost:3000/v1/books
Content-Type: application/json