package errors

const (
	GET_SUCCESS_CODE                = 200
	POST_SUCCESS_CODE               = 201
	PUT_NO_CONTENT_SUCCESS_CODE     = 204
	DELETE_NO_CONTENT_SUCCESS_CODE  = 204
	BAD_REQUEST_ERROR_CODE          = 400
	UNAUTHORIZED_ERROR_CODE         = 401
	FORBIDDEN_ERROR_CODE            = 403
	NOT_FOUND_ERROR_CODE            = 404
	METHOD_NOT_ALLOWED_ERROR_CODE   = 405
	REQUEST_TIMEOUT_ERROR_CODE      = 408
	CONFLICT_ERROR_CODE             = 409
	UNPROCESSABLE_ENTITY_ERROR_CODE = 422
	TOO_MANY_REQUESTS_ERROR_CODE    = 429
	INTERNAL_SERVER_ERROR_CODE      = 500
	NOT_IMPLEMENTED_ERROR_CODE      = 501
	BAD_GATEWAY_ERROR_CODE          = 502
	SERVICE_UNAVAILABLE_ERROR_CODE  = 503
	GATEWAY_TIMEOUT_ERROR_CODE      = 504
)
